export const JWT_SECRE_ACCESS_TOKEN = 'JWT_SECRE_ACCESS_TOKEN';
export const JWT_EXPIRESIN_ACCESS_TOKEN = 'JWT_EXPIRESIN_ACCESS_TOKEN';

export const JWT_SECRE_REFRESH_TOKEN = 'JWT_SECRE_REFRESH_TOKEN';
export const JWT_EXPIRESIN_REFRESH_TOKEN = 'JWT_EXPIRESIN_REFRESH_TOKEN';
